imports:
    - { resource: config.yml }

parameters:
    database_host:     localhost
    database_port:
    database_name:     mojeskoly
    database_user:     mojeskoly
    database_password: {{ pillar.mysql.user.mojeskoly.password }}
